packages:
  - .
  - ./amplify

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver

overrides:
  fast-xml-parser@>=4.0.0-beta.3 <=5.5.5: '>=5.5.6'
  immutable@<4.3.8: '>=4.3.8'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
