packages:
  - .
  - ./amplify

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver

overrides:
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
