packages:
  - .
  - ./amplify

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver

overrides:
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  diff@<8.0.3: '>=8.0.3'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
